/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.27
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.api;

import com.bytedance.ads.ApiCallback;
import com.bytedance.ads.ApiClient;
import com.bytedance.ads.ApiException;
import com.bytedance.ads.ApiResponse;
import com.bytedance.ads.Configuration;
import com.bytedance.ads.Pair;

import com.google.gson.reflect.TypeToken;



import com.bytedance.ads.model.LocalProductGetV30Filtering;
import com.bytedance.ads.model.LocalProductGetV30LocalDeliveryScene;
import com.bytedance.ads.model.LocalProductGetV30Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LocalProductGetV30Api {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LocalProductGetV30Api() {
        this(Configuration.getDefaultApiClient());
    }

    public LocalProductGetV30Api(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for openApiV30LocalProductGetGet
     * @param localAccountId 广告主ID (required)
     * @param localDeliveryScene  (required)
     * @param filtering 过滤器 (optional)
     * @param page 页码 (optional, default to 1)
     * @param pageSize 页面大小[1, 100] (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call openApiV30LocalProductGetGetCall(Long localAccountId, LocalProductGetV30LocalDeliveryScene localDeliveryScene, LocalProductGetV30Filtering filtering, Long page, Long pageSize, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/open_api/v3.0/local/product/get/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (localAccountId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("local_account_id", localAccountId));
        }

        if (localDeliveryScene != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("local_delivery_scene", localDeliveryScene));
        }

        if (filtering != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filtering", filtering));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call openApiV30LocalProductGetGetValidateBeforeCall(Long localAccountId, LocalProductGetV30LocalDeliveryScene localDeliveryScene, LocalProductGetV30Filtering filtering, Long page, Long pageSize, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'localAccountId' is set
        if (localAccountId == null) {
            throw new ApiException("Missing the required parameter 'localAccountId' when calling openApiV30LocalProductGetGet(Async)");
        }

        // verify the required parameter 'localDeliveryScene' is set
        if (localDeliveryScene == null) {
            throw new ApiException("Missing the required parameter 'localDeliveryScene' when calling openApiV30LocalProductGetGet(Async)");
        }

        return openApiV30LocalProductGetGetCall(localAccountId, localDeliveryScene, filtering, page, pageSize, _callback);

    }

    /**
     * 
     * 
     * @param localAccountId 广告主ID (required)
     * @param localDeliveryScene  (required)
     * @param filtering 过滤器 (optional)
     * @param page 页码 (optional, default to 1)
     * @param pageSize 页面大小[1, 100] (optional, default to 20)
     * @return LocalProductGetV30Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public LocalProductGetV30Response openApiV30LocalProductGetGet(Long localAccountId, LocalProductGetV30LocalDeliveryScene localDeliveryScene, LocalProductGetV30Filtering filtering, Long page, Long pageSize) throws ApiException {
        ApiResponse<LocalProductGetV30Response> localVarResp = openApiV30LocalProductGetGetWithHttpInfo(localAccountId, localDeliveryScene, filtering, page, pageSize);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param localAccountId 广告主ID (required)
     * @param localDeliveryScene  (required)
     * @param filtering 过滤器 (optional)
     * @param page 页码 (optional, default to 1)
     * @param pageSize 页面大小[1, 100] (optional, default to 20)
     * @return ApiResponse&lt;LocalProductGetV30Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocalProductGetV30Response> openApiV30LocalProductGetGetWithHttpInfo(Long localAccountId, LocalProductGetV30LocalDeliveryScene localDeliveryScene, LocalProductGetV30Filtering filtering, Long page, Long pageSize) throws ApiException {
        okhttp3.Call localVarCall = openApiV30LocalProductGetGetValidateBeforeCall(localAccountId, localDeliveryScene, filtering, page, pageSize, null);
        Type localVarReturnType = new TypeToken<LocalProductGetV30Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param localAccountId 广告主ID (required)
     * @param localDeliveryScene  (required)
     * @param filtering 过滤器 (optional)
     * @param page 页码 (optional, default to 1)
     * @param pageSize 页面大小[1, 100] (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call openApiV30LocalProductGetGetAsync(Long localAccountId, LocalProductGetV30LocalDeliveryScene localDeliveryScene, LocalProductGetV30Filtering filtering, Long page, Long pageSize, final ApiCallback<LocalProductGetV30Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = openApiV30LocalProductGetGetValidateBeforeCall(localAccountId, localDeliveryScene, filtering, page, pageSize, _callback);
        Type localVarReturnType = new TypeToken<LocalProductGetV30Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
