/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.65
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.examples;

import com.bytedance.ads.ApiException;
import com.bytedance.ads.api.StarMcnProviderUploadSearchItemV2Api;
import com.bytedance.ads.ApiClient;
import com.bytedance.ads.model.StarMcnProviderUploadSearchItemV2Request;
import com.bytedance.ads.model.StarMcnProviderUploadSearchItemV2Response;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

// url: https://api.oceanengine.com/open_api/2/star/mcn/provider_upload_search_item/ POST
public class StarMcnProviderUploadSearchItemV2ApiExample {

    private static final StarMcnProviderUploadSearchItemV2Api api = new StarMcnProviderUploadSearchItemV2Api();

    public static void main(String[] args) throws ApiException {
        StarMcnProviderUploadSearchItemV2Request starMcnProviderUploadSearchItemV2Request = null;
        ApiClient apiClient = api.getApiClient();
        apiClient.addDefaultHeader("Access-Token", "");
        apiClient.setDebugging(true);
        api.setApiClient(apiClient);
        StarMcnProviderUploadSearchItemV2Response response = api.openApi2StarMcnProviderUploadSearchItemPost(starMcnProviderUploadSearchItemV2Request);
        System.out.println(response);
    }

}