/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.81
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * 政策信息
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2026-01-04T17:46:59.440189234+08:00[Asia/Shanghai]")
public class BrandOrderListV30ResponseDataOrdersInnerPolicy {
  public static final String SERIALIZED_NAME_POLICY_NAME = "policy_name";
  @SerializedName(SERIALIZED_NAME_POLICY_NAME)
  private String policyName = null;

  public static final String SERIALIZED_NAME_POLICY_NO = "policy_no";
  @SerializedName(SERIALIZED_NAME_POLICY_NO)
  private String policyNo = null;

  public static final String SERIALIZED_NAME_POLICY_TYPE = "policy_type";
  @SerializedName(SERIALIZED_NAME_POLICY_TYPE)
  private String policyType = null;

  public static final String SERIALIZED_NAME_POLICY_TYPE_NAME = "policy_type_name";
  @SerializedName(SERIALIZED_NAME_POLICY_TYPE_NAME)
  private String policyTypeName = null;

  public BrandOrderListV30ResponseDataOrdersInnerPolicy() {
  }

  public BrandOrderListV30ResponseDataOrdersInnerPolicy policyName(String policyName) {
    
    this.policyName = policyName;
    return this;
  }

   /**
   * 政策名称
   * @return policyName
  **/
  @javax.annotation.Nullable
  public String getPolicyName() {
    return policyName;
  }


  public void setPolicyName(String policyName) {
    this.policyName = policyName;
  }


  public BrandOrderListV30ResponseDataOrdersInnerPolicy policyNo(String policyNo) {
    
    this.policyNo = policyNo;
    return this;
  }

   /**
   * 政策编号
   * @return policyNo
  **/
  @javax.annotation.Nullable
  public String getPolicyNo() {
    return policyNo;
  }


  public void setPolicyNo(String policyNo) {
    this.policyNo = policyNo;
  }


  public BrandOrderListV30ResponseDataOrdersInnerPolicy policyType(String policyType) {
    
    this.policyType = policyType;
    return this;
  }

   /**
   * 政策类型
   * @return policyType
  **/
  @javax.annotation.Nullable
  public String getPolicyType() {
    return policyType;
  }


  public void setPolicyType(String policyType) {
    this.policyType = policyType;
  }


  public BrandOrderListV30ResponseDataOrdersInnerPolicy policyTypeName(String policyTypeName) {
    
    this.policyTypeName = policyTypeName;
    return this;
  }

   /**
   * 政策类型名称
   * @return policyTypeName
  **/
  @javax.annotation.Nullable
  public String getPolicyTypeName() {
    return policyTypeName;
  }


  public void setPolicyTypeName(String policyTypeName) {
    this.policyTypeName = policyTypeName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandOrderListV30ResponseDataOrdersInnerPolicy brandOrderListV30ResponseDataOrdersInnerPolicy = (BrandOrderListV30ResponseDataOrdersInnerPolicy) o;
    return Objects.equals(this.policyName, brandOrderListV30ResponseDataOrdersInnerPolicy.policyName) &&
        Objects.equals(this.policyNo, brandOrderListV30ResponseDataOrdersInnerPolicy.policyNo) &&
        Objects.equals(this.policyType, brandOrderListV30ResponseDataOrdersInnerPolicy.policyType) &&
        Objects.equals(this.policyTypeName, brandOrderListV30ResponseDataOrdersInnerPolicy.policyTypeName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyName, policyNo, policyType, policyTypeName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandOrderListV30ResponseDataOrdersInnerPolicy {\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("    policyNo: ").append(toIndentedString(policyNo)).append("\n");
    sb.append("    policyType: ").append(toIndentedString(policyType)).append("\n");
    sb.append("    policyTypeName: ").append(toIndentedString(policyTypeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("policy_name");
    openapiFields.add("policy_no");
    openapiFields.add("policy_type");
    openapiFields.add("policy_type_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BrandOrderListV30ResponseDataOrdersInnerPolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BrandOrderListV30ResponseDataOrdersInnerPolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BrandOrderListV30ResponseDataOrdersInnerPolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BrandOrderListV30ResponseDataOrdersInnerPolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<BrandOrderListV30ResponseDataOrdersInnerPolicy>() {
           @Override
           public void write(JsonWriter out, BrandOrderListV30ResponseDataOrdersInnerPolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BrandOrderListV30ResponseDataOrdersInnerPolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BrandOrderListV30ResponseDataOrdersInnerPolicy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BrandOrderListV30ResponseDataOrdersInnerPolicy
  * @throws IOException if the JSON string is invalid with respect to BrandOrderListV30ResponseDataOrdersInnerPolicy
  */
  public static BrandOrderListV30ResponseDataOrdersInnerPolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BrandOrderListV30ResponseDataOrdersInnerPolicy.class);
  }

 /**
  * Convert an instance of BrandOrderListV30ResponseDataOrdersInnerPolicy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

