/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.97
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2026-09-29T16:33:15.300170006+08:00[Asia/Shanghai]")
public class BrandMaMaterialListV30OrderFilter {
  public static final String SERIALIZED_NAME_AD_FORM = "ad_form";
  @SerializedName(SERIALIZED_NAME_AD_FORM)
  private List<Long> adForm = null;

  public static final String SERIALIZED_NAME_ADVANCED_OPTION = "advanced_option";
  @SerializedName(SERIALIZED_NAME_ADVANCED_OPTION)
  private Long advancedOption = null;

  public static final String SERIALIZED_NAME_APP_ORIGIN = "app_origin";
  @SerializedName(SERIALIZED_NAME_APP_ORIGIN)
  private Long appOrigin = null;

  public static final String SERIALIZED_NAME_CREATE_END_TIME = "create_end_time";
  @SerializedName(SERIALIZED_NAME_CREATE_END_TIME)
  private String createEndTime = null;

  public static final String SERIALIZED_NAME_CREATE_START_TIME = "create_start_time";
  @SerializedName(SERIALIZED_NAME_CREATE_START_TIME)
  private String createStartTime = null;

  public static final String SERIALIZED_NAME_GD_SEND_TYPE = "gd_send_type";
  @SerializedName(SERIALIZED_NAME_GD_SEND_TYPE)
  private Long gdSendType = null;

  public static final String SERIALIZED_NAME_ORDER_END_TIME = "order_end_time";
  @SerializedName(SERIALIZED_NAME_ORDER_END_TIME)
  private String orderEndTime = null;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private String orderId = null;

  public static final String SERIALIZED_NAME_ORDER_NAME = "order_name";
  @SerializedName(SERIALIZED_NAME_ORDER_NAME)
  private String orderName = null;

  public static final String SERIALIZED_NAME_ORDER_START_TIME = "order_start_time";
  @SerializedName(SERIALIZED_NAME_ORDER_START_TIME)
  private String orderStartTime = null;

  public static final String SERIALIZED_NAME_ORDER_STATUS = "order_status";
  @SerializedName(SERIALIZED_NAME_ORDER_STATUS)
  private List<Long> orderStatus = null;

  public static final String SERIALIZED_NAME_PRO_TYPE = "pro_type";
  @SerializedName(SERIALIZED_NAME_PRO_TYPE)
  private Long proType = null;

  public BrandMaMaterialListV30OrderFilter() {
  }

  public BrandMaMaterialListV30OrderFilter adForm(List<Long> adForm) {
    
    this.adForm = adForm;
    return this;
  }

  public BrandMaMaterialListV30OrderFilter addAdFormItem(Long adFormItem) {
    if (this.adForm == null) {
      this.adForm = new ArrayList<>();
    }
    this.adForm.add(adFormItem);
    return this;
  }

   /**
   * 产品类型
   * @return adForm
  **/
  @javax.annotation.Nullable
  public List<Long> getAdForm() {
    return adForm;
  }


  public void setAdForm(List<Long> adForm) {
    this.adForm = adForm;
  }


  public BrandMaMaterialListV30OrderFilter advancedOption(Long advancedOption) {
    
    this.advancedOption = advancedOption;
    return this;
  }

   /**
   * 进阶选项
   * @return advancedOption
  **/
  @javax.annotation.Nullable
  public Long getAdvancedOption() {
    return advancedOption;
  }


  public void setAdvancedOption(Long advancedOption) {
    this.advancedOption = advancedOption;
  }


  public BrandMaMaterialListV30OrderFilter appOrigin(Long appOrigin) {
    
    this.appOrigin = appOrigin;
    return this;
  }

   /**
   * 投放位置
   * @return appOrigin
  **/
  @javax.annotation.Nullable
  public Long getAppOrigin() {
    return appOrigin;
  }


  public void setAppOrigin(Long appOrigin) {
    this.appOrigin = appOrigin;
  }


  public BrandMaMaterialListV30OrderFilter createEndTime(String createEndTime) {
    
    this.createEndTime = createEndTime;
    return this;
  }

   /**
   * 预订单创建结束时间
   * @return createEndTime
  **/
  @javax.annotation.Nullable
  public String getCreateEndTime() {
    return createEndTime;
  }


  public void setCreateEndTime(String createEndTime) {
    this.createEndTime = createEndTime;
  }


  public BrandMaMaterialListV30OrderFilter createStartTime(String createStartTime) {
    
    this.createStartTime = createStartTime;
    return this;
  }

   /**
   * 预订单创建开始时间
   * @return createStartTime
  **/
  @javax.annotation.Nullable
  public String getCreateStartTime() {
    return createStartTime;
  }


  public void setCreateStartTime(String createStartTime) {
    this.createStartTime = createStartTime;
  }


  public BrandMaMaterialListV30OrderFilter gdSendType(Long gdSendType) {
    
    this.gdSendType = gdSendType;
    return this;
  }

   /**
   * 优化目标
   * @return gdSendType
  **/
  @javax.annotation.Nullable
  public Long getGdSendType() {
    return gdSendType;
  }


  public void setGdSendType(Long gdSendType) {
    this.gdSendType = gdSendType;
  }


  public BrandMaMaterialListV30OrderFilter orderEndTime(String orderEndTime) {
    
    this.orderEndTime = orderEndTime;
    return this;
  }

   /**
   * 预订单结束开始时间
   * @return orderEndTime
  **/
  @javax.annotation.Nullable
  public String getOrderEndTime() {
    return orderEndTime;
  }


  public void setOrderEndTime(String orderEndTime) {
    this.orderEndTime = orderEndTime;
  }


  public BrandMaMaterialListV30OrderFilter orderId(String orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * 预定单ID
   * @return orderId
  **/
  @javax.annotation.Nullable
  public String getOrderId() {
    return orderId;
  }


  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }


  public BrandMaMaterialListV30OrderFilter orderName(String orderName) {
    
    this.orderName = orderName;
    return this;
  }

   /**
   * 预订单名称
   * @return orderName
  **/
  @javax.annotation.Nullable
  public String getOrderName() {
    return orderName;
  }


  public void setOrderName(String orderName) {
    this.orderName = orderName;
  }


  public BrandMaMaterialListV30OrderFilter orderStartTime(String orderStartTime) {
    
    this.orderStartTime = orderStartTime;
    return this;
  }

   /**
   * 预订单投放开始时间
   * @return orderStartTime
  **/
  @javax.annotation.Nullable
  public String getOrderStartTime() {
    return orderStartTime;
  }


  public void setOrderStartTime(String orderStartTime) {
    this.orderStartTime = orderStartTime;
  }


  public BrandMaMaterialListV30OrderFilter orderStatus(List<Long> orderStatus) {
    
    this.orderStatus = orderStatus;
    return this;
  }

  public BrandMaMaterialListV30OrderFilter addOrderStatusItem(Long orderStatusItem) {
    if (this.orderStatus == null) {
      this.orderStatus = new ArrayList<>();
    }
    this.orderStatus.add(orderStatusItem);
    return this;
  }

   /**
   * 预订单状态
   * @return orderStatus
  **/
  @javax.annotation.Nullable
  public List<Long> getOrderStatus() {
    return orderStatus;
  }


  public void setOrderStatus(List<Long> orderStatus) {
    this.orderStatus = orderStatus;
  }


  public BrandMaMaterialListV30OrderFilter proType(Long proType) {
    
    this.proType = proType;
    return this;
  }

   /**
   * 投放产品
   * @return proType
  **/
  @javax.annotation.Nullable
  public Long getProType() {
    return proType;
  }


  public void setProType(Long proType) {
    this.proType = proType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandMaMaterialListV30OrderFilter brandMaMaterialListV30OrderFilter = (BrandMaMaterialListV30OrderFilter) o;
    return Objects.equals(this.adForm, brandMaMaterialListV30OrderFilter.adForm) &&
        Objects.equals(this.advancedOption, brandMaMaterialListV30OrderFilter.advancedOption) &&
        Objects.equals(this.appOrigin, brandMaMaterialListV30OrderFilter.appOrigin) &&
        Objects.equals(this.createEndTime, brandMaMaterialListV30OrderFilter.createEndTime) &&
        Objects.equals(this.createStartTime, brandMaMaterialListV30OrderFilter.createStartTime) &&
        Objects.equals(this.gdSendType, brandMaMaterialListV30OrderFilter.gdSendType) &&
        Objects.equals(this.orderEndTime, brandMaMaterialListV30OrderFilter.orderEndTime) &&
        Objects.equals(this.orderId, brandMaMaterialListV30OrderFilter.orderId) &&
        Objects.equals(this.orderName, brandMaMaterialListV30OrderFilter.orderName) &&
        Objects.equals(this.orderStartTime, brandMaMaterialListV30OrderFilter.orderStartTime) &&
        Objects.equals(this.orderStatus, brandMaMaterialListV30OrderFilter.orderStatus) &&
        Objects.equals(this.proType, brandMaMaterialListV30OrderFilter.proType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adForm, advancedOption, appOrigin, createEndTime, createStartTime, gdSendType, orderEndTime, orderId, orderName, orderStartTime, orderStatus, proType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandMaMaterialListV30OrderFilter {\n");
    sb.append("    adForm: ").append(toIndentedString(adForm)).append("\n");
    sb.append("    advancedOption: ").append(toIndentedString(advancedOption)).append("\n");
    sb.append("    appOrigin: ").append(toIndentedString(appOrigin)).append("\n");
    sb.append("    createEndTime: ").append(toIndentedString(createEndTime)).append("\n");
    sb.append("    createStartTime: ").append(toIndentedString(createStartTime)).append("\n");
    sb.append("    gdSendType: ").append(toIndentedString(gdSendType)).append("\n");
    sb.append("    orderEndTime: ").append(toIndentedString(orderEndTime)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderName: ").append(toIndentedString(orderName)).append("\n");
    sb.append("    orderStartTime: ").append(toIndentedString(orderStartTime)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    proType: ").append(toIndentedString(proType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ad_form");
    openapiFields.add("advanced_option");
    openapiFields.add("app_origin");
    openapiFields.add("create_end_time");
    openapiFields.add("create_start_time");
    openapiFields.add("gd_send_type");
    openapiFields.add("order_end_time");
    openapiFields.add("order_id");
    openapiFields.add("order_name");
    openapiFields.add("order_start_time");
    openapiFields.add("order_status");
    openapiFields.add("pro_type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BrandMaMaterialListV30OrderFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BrandMaMaterialListV30OrderFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BrandMaMaterialListV30OrderFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BrandMaMaterialListV30OrderFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<BrandMaMaterialListV30OrderFilter>() {
           @Override
           public void write(JsonWriter out, BrandMaMaterialListV30OrderFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BrandMaMaterialListV30OrderFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BrandMaMaterialListV30OrderFilter given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BrandMaMaterialListV30OrderFilter
  * @throws IOException if the JSON string is invalid with respect to BrandMaMaterialListV30OrderFilter
  */
  public static BrandMaMaterialListV30OrderFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BrandMaMaterialListV30OrderFilter.class);
  }

 /**
  * Convert an instance of BrandMaMaterialListV30OrderFilter to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

