/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.90
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 品牌数据来源
 */
@JsonAdapter(DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource.Adapter.class)
public enum DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource {
  
  YUNTU("YUNTU");

  private String value;

  DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource fromValue(String value) {
    for (DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource b : DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource> {
    @Override
    public void write(final JsonWriter jsonWriter, final DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DpaBrandAdvAuthIndustryGetV30OriginReqBrandDataSource.fromValue(value);
    }
  }
}

