/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.78
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.bytedance.ads.model.DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfoTargetUrl;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * 品牌信息
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2025-12-23T11:52:48.108420764+08:00[Asia/Shanghai]")
public class DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo {
  public static final String SERIALIZED_NAME_BRAND_ID = "brand_id";
  @SerializedName(SERIALIZED_NAME_BRAND_ID)
  private String brandId = null;

  public static final String SERIALIZED_NAME_BRAND_LOGO = "brand_logo";
  @SerializedName(SERIALIZED_NAME_BRAND_LOGO)
  private String brandLogo = null;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brand_name";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  private String brandName = null;

  public static final String SERIALIZED_NAME_BRAND_OWNER = "brand_owner";
  @SerializedName(SERIALIZED_NAME_BRAND_OWNER)
  private String brandOwner = null;

  public static final String SERIALIZED_NAME_EN_BRAND = "en_brand";
  @SerializedName(SERIALIZED_NAME_EN_BRAND)
  private String enBrand = null;

  public static final String SERIALIZED_NAME_TARGET_URL = "target_url";
  @SerializedName(SERIALIZED_NAME_TARGET_URL)
  private DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfoTargetUrl targetUrl = null;

  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo() {
  }

  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo brandId(String brandId) {
    
    this.brandId = brandId;
    return this;
  }

   /**
   * 
   * @return brandId
  **/
  @javax.annotation.Nullable
  public String getBrandId() {
    return brandId;
  }


  public void setBrandId(String brandId) {
    this.brandId = brandId;
  }


  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo brandLogo(String brandLogo) {
    
    this.brandLogo = brandLogo;
    return this;
  }

   /**
   * 
   * @return brandLogo
  **/
  @javax.annotation.Nullable
  public String getBrandLogo() {
    return brandLogo;
  }


  public void setBrandLogo(String brandLogo) {
    this.brandLogo = brandLogo;
  }


  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo brandName(String brandName) {
    
    this.brandName = brandName;
    return this;
  }

   /**
   * 
   * @return brandName
  **/
  @javax.annotation.Nullable
  public String getBrandName() {
    return brandName;
  }


  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }


  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo brandOwner(String brandOwner) {
    
    this.brandOwner = brandOwner;
    return this;
  }

   /**
   * 所属集团名称
   * @return brandOwner
  **/
  @javax.annotation.Nullable
  public String getBrandOwner() {
    return brandOwner;
  }


  public void setBrandOwner(String brandOwner) {
    this.brandOwner = brandOwner;
  }


  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo enBrand(String enBrand) {
    
    this.enBrand = enBrand;
    return this;
  }

   /**
   * 
   * @return enBrand
  **/
  @javax.annotation.Nullable
  public String getEnBrand() {
    return enBrand;
  }


  public void setEnBrand(String enBrand) {
    this.enBrand = enBrand;
  }


  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo targetUrl(DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfoTargetUrl targetUrl) {
    
    this.targetUrl = targetUrl;
    return this;
  }

   /**
   * Get targetUrl
   * @return targetUrl
  **/
  @javax.annotation.Nullable
  public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfoTargetUrl getTargetUrl() {
    return targetUrl;
  }


  public void setTargetUrl(DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfoTargetUrl targetUrl) {
    this.targetUrl = targetUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo = (DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo) o;
    return Objects.equals(this.brandId, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.brandId) &&
        Objects.equals(this.brandLogo, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.brandLogo) &&
        Objects.equals(this.brandName, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.brandName) &&
        Objects.equals(this.brandOwner, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.brandOwner) &&
        Objects.equals(this.enBrand, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.enBrand) &&
        Objects.equals(this.targetUrl, dpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.targetUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(brandId, brandLogo, brandName, brandOwner, enBrand, targetUrl);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo {\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    brandLogo: ").append(toIndentedString(brandLogo)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    brandOwner: ").append(toIndentedString(brandOwner)).append("\n");
    sb.append("    enBrand: ").append(toIndentedString(enBrand)).append("\n");
    sb.append("    targetUrl: ").append(toIndentedString(targetUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("brand_id");
    openapiFields.add("brand_logo");
    openapiFields.add("brand_name");
    openapiFields.add("brand_owner");
    openapiFields.add("en_brand");
    openapiFields.add("target_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo>() {
           @Override
           public void write(JsonWriter out, DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo
  * @throws IOException if the JSON string is invalid with respect to DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo
  */
  public static DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo.class);
  }

 /**
  * Convert an instance of DpaEbpClueProductListV30ResponseDataProductsInnerBrandInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

