/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.bytedance.ads.model.LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform;
import com.bytedance.ads.model.LocalPromotionRejectReasonGetV30DataListMaterialRejectType;
import com.bytedance.ads.model.LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner;
import com.bytedance.ads.model.LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2025-12-23T14:17:43.061643537+08:00[Asia/Shanghai]")
public class LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner {
  public static final String SERIALIZED_NAME_AUDIT_PLATFORM = "audit_platform";
  @SerializedName(SERIALIZED_NAME_AUDIT_PLATFORM)
  private LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform auditPlatform = null;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content = null;

  public static final String SERIALIZED_NAME_IMAGE_MATERIAL = "image_material";
  @SerializedName(SERIALIZED_NAME_IMAGE_MATERIAL)
  private List<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner> imageMaterial = null;

  public static final String SERIALIZED_NAME_REJECT_REASON = "reject_reason";
  @SerializedName(SERIALIZED_NAME_REJECT_REASON)
  private List<String> rejectReason = null;

  public static final String SERIALIZED_NAME_SUGGESTION = "suggestion";
  @SerializedName(SERIALIZED_NAME_SUGGESTION)
  private List<String> suggestion = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private LocalPromotionRejectReasonGetV30DataListMaterialRejectType type = null;

  public static final String SERIALIZED_NAME_VIDEO_MATERIAL = "video_material";
  @SerializedName(SERIALIZED_NAME_VIDEO_MATERIAL)
  private LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial videoMaterial = null;

  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner() {
  }

  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner auditPlatform(LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform auditPlatform) {
    
    this.auditPlatform = auditPlatform;
    return this;
  }

   /**
   * Get auditPlatform
   * @return auditPlatform
  **/
  @javax.annotation.Nullable
  public LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform getAuditPlatform() {
    return auditPlatform;
  }


  public void setAuditPlatform(LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform auditPlatform) {
    this.auditPlatform = auditPlatform;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * 审核拒绝的具体内容
   * @return content
  **/
  @javax.annotation.Nullable
  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    this.content = content;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner imageMaterial(List<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner> imageMaterial) {
    
    this.imageMaterial = imageMaterial;
    return this;
  }

  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner addImageMaterialItem(LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner imageMaterialItem) {
    if (this.imageMaterial == null) {
      this.imageMaterial = new ArrayList<>();
    }
    this.imageMaterial.add(imageMaterialItem);
    return this;
  }

   /**
   * 
   * @return imageMaterial
  **/
  @javax.annotation.Nullable
  public List<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner> getImageMaterial() {
    return imageMaterial;
  }


  public void setImageMaterial(List<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner> imageMaterial) {
    this.imageMaterial = imageMaterial;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner rejectReason(List<String> rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner addRejectReasonItem(String rejectReasonItem) {
    if (this.rejectReason == null) {
      this.rejectReason = new ArrayList<>();
    }
    this.rejectReason.add(rejectReasonItem);
    return this;
  }

   /**
   * 拒绝理由
   * @return rejectReason
  **/
  @javax.annotation.Nullable
  public List<String> getRejectReason() {
    return rejectReason;
  }


  public void setRejectReason(List<String> rejectReason) {
    this.rejectReason = rejectReason;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner suggestion(List<String> suggestion) {
    
    this.suggestion = suggestion;
    return this;
  }

  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner addSuggestionItem(String suggestionItem) {
    if (this.suggestion == null) {
      this.suggestion = new ArrayList<>();
    }
    this.suggestion.add(suggestionItem);
    return this;
  }

   /**
   * 审核建议
   * @return suggestion
  **/
  @javax.annotation.Nullable
  public List<String> getSuggestion() {
    return suggestion;
  }


  public void setSuggestion(List<String> suggestion) {
    this.suggestion = suggestion;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner type(LocalPromotionRejectReasonGetV30DataListMaterialRejectType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  public LocalPromotionRejectReasonGetV30DataListMaterialRejectType getType() {
    return type;
  }


  public void setType(LocalPromotionRejectReasonGetV30DataListMaterialRejectType type) {
    this.type = type;
  }


  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner videoMaterial(LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial videoMaterial) {
    
    this.videoMaterial = videoMaterial;
    return this;
  }

   /**
   * Get videoMaterial
   * @return videoMaterial
  **/
  @javax.annotation.Nullable
  public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial getVideoMaterial() {
    return videoMaterial;
  }


  public void setVideoMaterial(LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial videoMaterial) {
    this.videoMaterial = videoMaterial;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner = (LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner) o;
    return Objects.equals(this.auditPlatform, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.auditPlatform) &&
        Objects.equals(this.content, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.content) &&
        Objects.equals(this.imageMaterial, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.imageMaterial) &&
        Objects.equals(this.rejectReason, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.rejectReason) &&
        Objects.equals(this.suggestion, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.suggestion) &&
        Objects.equals(this.type, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.type) &&
        Objects.equals(this.videoMaterial, localPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.videoMaterial);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditPlatform, content, imageMaterial, rejectReason, suggestion, type, videoMaterial);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner {\n");
    sb.append("    auditPlatform: ").append(toIndentedString(auditPlatform)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    imageMaterial: ").append(toIndentedString(imageMaterial)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    suggestion: ").append(toIndentedString(suggestion)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    videoMaterial: ").append(toIndentedString(videoMaterial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("audit_platform");
    openapiFields.add("content");
    openapiFields.add("image_material");
    openapiFields.add("reject_reason");
    openapiFields.add("suggestion");
    openapiFields.add("type");
    openapiFields.add("video_material");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.class));

       return (TypeAdapter<T>) new TypeAdapter<LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner>() {
           @Override
           public void write(JsonWriter out, LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner
  * @throws IOException if the JSON string is invalid with respect to LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner
  */
  public static LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner.class);
  }

 /**
  * Convert an instance of LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

