/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 预算类型
 */
@JsonAdapter(LocalAdvertiserBudgetGetV30DataListBudgetMode.Adapter.class)
public enum LocalAdvertiserBudgetGetV30DataListBudgetMode {
  
  ALL("ALL"),
  
  BUDGET_MODE_DAY("BUDGET_MODE_DAY"),
  
  BUDGET_MODE_TOTAL("BUDGET_MODE_TOTAL");

  private String value;

  LocalAdvertiserBudgetGetV30DataListBudgetMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LocalAdvertiserBudgetGetV30DataListBudgetMode fromValue(String value) {
    for (LocalAdvertiserBudgetGetV30DataListBudgetMode b : LocalAdvertiserBudgetGetV30DataListBudgetMode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LocalAdvertiserBudgetGetV30DataListBudgetMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final LocalAdvertiserBudgetGetV30DataListBudgetMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LocalAdvertiserBudgetGetV30DataListBudgetMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LocalAdvertiserBudgetGetV30DataListBudgetMode.fromValue(value);
    }
  }
}

