/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.72
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 取值VID|FILEID，VID含义为火山点播视频片源ID，FILEID为火山点播某个Vid下的转码产物ID
 */
@JsonAdapter(OpenMaterialAuditProSubmitV30InputType.Adapter.class)
public enum OpenMaterialAuditProSubmitV30InputType {
  
  VID("VID"),
  
  FILELD("FILELD");

  private String value;

  OpenMaterialAuditProSubmitV30InputType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OpenMaterialAuditProSubmitV30InputType fromValue(String value) {
    for (OpenMaterialAuditProSubmitV30InputType b : OpenMaterialAuditProSubmitV30InputType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OpenMaterialAuditProSubmitV30InputType> {
    @Override
    public void write(final JsonWriter jsonWriter, final OpenMaterialAuditProSubmitV30InputType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OpenMaterialAuditProSubmitV30InputType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OpenMaterialAuditProSubmitV30InputType.fromValue(value);
    }
  }
}

