/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.75
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.bytedance.ads.model.PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListImageMode;
import com.bytedance.ads.model.PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialOptStatus;
import com.bytedance.ads.model.PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2025-11-25T21:45:26.590033936+08:00[Asia/Shanghai]")
public class PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner {
  public static final String SERIALIZED_NAME_APP_PLAY_URI = "app_play_uri";
  @SerializedName(SERIALIZED_NAME_APP_PLAY_URI)
  private String appPlayUri = null;

  public static final String SERIALIZED_NAME_APP_PLAY_VERSION = "app_play_version";
  @SerializedName(SERIALIZED_NAME_APP_PLAY_VERSION)
  private String appPlayVersion = null;

  public static final String SERIALIZED_NAME_FILE_NAME = "file_name";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName = null;

  public static final String SERIALIZED_NAME_GUIDE_VIDEO_ID = "guide_video_id";
  @SerializedName(SERIALIZED_NAME_GUIDE_VIDEO_ID)
  private String guideVideoId = null;

  public static final String SERIALIZED_NAME_IMAGE_MODE = "image_mode";
  @SerializedName(SERIALIZED_NAME_IMAGE_MODE)
  private PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListImageMode imageMode = null;

  public static final String SERIALIZED_NAME_MATERIAL_ID = "material_id";
  @SerializedName(SERIALIZED_NAME_MATERIAL_ID)
  private Long materialId = null;

  public static final String SERIALIZED_NAME_MATERIAL_OPT_STATUS = "material_opt_status";
  @SerializedName(SERIALIZED_NAME_MATERIAL_OPT_STATUS)
  private PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialOptStatus materialOptStatus = null;

  public static final String SERIALIZED_NAME_MATERIAL_STATUS = "material_status";
  @SerializedName(SERIALIZED_NAME_MATERIAL_STATUS)
  private PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialStatus materialStatus = null;

  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner() {
  }

  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner appPlayUri(String appPlayUri) {
    
    this.appPlayUri = appPlayUri;
    return this;
  }

   /**
   * 
   * @return appPlayUri
  **/
  @javax.annotation.Nullable
  public String getAppPlayUri() {
    return appPlayUri;
  }


  public void setAppPlayUri(String appPlayUri) {
    this.appPlayUri = appPlayUri;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner appPlayVersion(String appPlayVersion) {
    
    this.appPlayVersion = appPlayVersion;
    return this;
  }

   /**
   * 
   * @return appPlayVersion
  **/
  @javax.annotation.Nullable
  public String getAppPlayVersion() {
    return appPlayVersion;
  }


  public void setAppPlayVersion(String appPlayVersion) {
    this.appPlayVersion = appPlayVersion;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * 
   * @return fileName
  **/
  @javax.annotation.Nullable
  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner guideVideoId(String guideVideoId) {
    
    this.guideVideoId = guideVideoId;
    return this;
  }

   /**
   * 
   * @return guideVideoId
  **/
  @javax.annotation.Nullable
  public String getGuideVideoId() {
    return guideVideoId;
  }


  public void setGuideVideoId(String guideVideoId) {
    this.guideVideoId = guideVideoId;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner imageMode(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListImageMode imageMode) {
    
    this.imageMode = imageMode;
    return this;
  }

   /**
   * Get imageMode
   * @return imageMode
  **/
  @javax.annotation.Nullable
  public PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListImageMode getImageMode() {
    return imageMode;
  }


  public void setImageMode(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListImageMode imageMode) {
    this.imageMode = imageMode;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner materialId(Long materialId) {
    
    this.materialId = materialId;
    return this;
  }

   /**
   * 
   * @return materialId
  **/
  @javax.annotation.Nullable
  public Long getMaterialId() {
    return materialId;
  }


  public void setMaterialId(Long materialId) {
    this.materialId = materialId;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner materialOptStatus(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialOptStatus materialOptStatus) {
    
    this.materialOptStatus = materialOptStatus;
    return this;
  }

   /**
   * Get materialOptStatus
   * @return materialOptStatus
  **/
  @javax.annotation.Nullable
  public PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialOptStatus getMaterialOptStatus() {
    return materialOptStatus;
  }


  public void setMaterialOptStatus(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialOptStatus materialOptStatus) {
    this.materialOptStatus = materialOptStatus;
  }


  public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner materialStatus(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialStatus materialStatus) {
    
    this.materialStatus = materialStatus;
    return this;
  }

   /**
   * Get materialStatus
   * @return materialStatus
  **/
  @javax.annotation.Nullable
  public PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialStatus getMaterialStatus() {
    return materialStatus;
  }


  public void setMaterialStatus(PromotionListV30DataListPromotionMaterialsTrialPlayMaterialListMaterialStatus materialStatus) {
    this.materialStatus = materialStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner = (PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner) o;
    return Objects.equals(this.appPlayUri, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.appPlayUri) &&
        Objects.equals(this.appPlayVersion, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.appPlayVersion) &&
        Objects.equals(this.fileName, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.fileName) &&
        Objects.equals(this.guideVideoId, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.guideVideoId) &&
        Objects.equals(this.imageMode, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.imageMode) &&
        Objects.equals(this.materialId, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.materialId) &&
        Objects.equals(this.materialOptStatus, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.materialOptStatus) &&
        Objects.equals(this.materialStatus, promotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.materialStatus);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(appPlayUri, appPlayVersion, fileName, guideVideoId, imageMode, materialId, materialOptStatus, materialStatus);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner {\n");
    sb.append("    appPlayUri: ").append(toIndentedString(appPlayUri)).append("\n");
    sb.append("    appPlayVersion: ").append(toIndentedString(appPlayVersion)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    guideVideoId: ").append(toIndentedString(guideVideoId)).append("\n");
    sb.append("    imageMode: ").append(toIndentedString(imageMode)).append("\n");
    sb.append("    materialId: ").append(toIndentedString(materialId)).append("\n");
    sb.append("    materialOptStatus: ").append(toIndentedString(materialOptStatus)).append("\n");
    sb.append("    materialStatus: ").append(toIndentedString(materialStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("app_play_uri");
    openapiFields.add("app_play_version");
    openapiFields.add("file_name");
    openapiFields.add("guide_video_id");
    openapiFields.add("image_mode");
    openapiFields.add("material_id");
    openapiFields.add("material_opt_status");
    openapiFields.add("material_status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner>() {
           @Override
           public void write(JsonWriter out, PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner
  * @throws IOException if the JSON string is invalid with respect to PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner
  */
  public static PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner.class);
  }

 /**
  * Convert an instance of PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

