/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.66
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 订单状态过滤
 */
@JsonAdapter(QianchuanAwemeUniPromotionOrderGetV10FilteringStatus.Adapter.class)
public enum QianchuanAwemeUniPromotionOrderGetV10FilteringStatus {
  
  AUDIT("AUDIT"),
  
  BOOK("BOOK"),
  
  CREATING("CREATING"),
  
  DELIVERY_OK("DELIVERY_OK"),
  
  FAILED("FAILED"),
  
  FINISHED("FINISHED"),
  
  FROZEN("FROZEN"),
  
  OFFLINE_AUDIT("OFFLINE_AUDIT"),
  
  OVER("OVER"),
  
  TIMEOUT("TIMEOUT"),
  
  UNPAID("UNPAID"),
  
  UNPAIDCANCEL("UNPAIDCANCEL");

  private String value;

  QianchuanAwemeUniPromotionOrderGetV10FilteringStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QianchuanAwemeUniPromotionOrderGetV10FilteringStatus fromValue(String value) {
    for (QianchuanAwemeUniPromotionOrderGetV10FilteringStatus b : QianchuanAwemeUniPromotionOrderGetV10FilteringStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<QianchuanAwemeUniPromotionOrderGetV10FilteringStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final QianchuanAwemeUniPromotionOrderGetV10FilteringStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public QianchuanAwemeUniPromotionOrderGetV10FilteringStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return QianchuanAwemeUniPromotionOrderGetV10FilteringStatus.fromValue(value);
    }
  }
}

