/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.81
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.bytedance.ads.model.StarVasGetBoostGroupOptionsV2DataDistrictSubRegionSubRegionDistrictType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2026-01-04T17:46:59.440189234+08:00[Asia/Shanghai]")
public class StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code = null;

  public static final String SERIALIZED_NAME_DISTRICT_TYPE = "district_type";
  @SerializedName(SERIALIZED_NAME_DISTRICT_TYPE)
  private StarVasGetBoostGroupOptionsV2DataDistrictSubRegionSubRegionDistrictType districtType = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner() {
  }

  public StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * 地域代码
   * @return code
  **/
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner districtType(StarVasGetBoostGroupOptionsV2DataDistrictSubRegionSubRegionDistrictType districtType) {
    
    this.districtType = districtType;
    return this;
  }

   /**
   * Get districtType
   * @return districtType
  **/
  @javax.annotation.Nullable
  public StarVasGetBoostGroupOptionsV2DataDistrictSubRegionSubRegionDistrictType getDistrictType() {
    return districtType;
  }


  public void setDistrictType(StarVasGetBoostGroupOptionsV2DataDistrictSubRegionSubRegionDistrictType districtType) {
    this.districtType = districtType;
  }


  public StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * 地域名称
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner starVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner = (StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner) o;
    return Objects.equals(this.code, starVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.code) &&
        Objects.equals(this.districtType, starVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.districtType) &&
        Objects.equals(this.name, starVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, districtType, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    districtType: ").append(toIndentedString(districtType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("code");
    openapiFields.add("district_type");
    openapiFields.add("name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("code");
    openapiRequiredFields.add("district_type");
    openapiRequiredFields.add("name");
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.class));

       return (TypeAdapter<T>) new TypeAdapter<StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner>() {
           @Override
           public void write(JsonWriter out, StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner
  * @throws IOException if the JSON string is invalid with respect to StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner
  */
  public static StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner.class);
  }

 /**
  * Convert an instance of StarVasGetBoostGroupOptionsV2ResponseDataDistrictInnerSubRegionInnerSubRegionInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

