/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.82
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.bytedance.ads.model.ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.bytedance.ads.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "com.org.bytedance.ad_open_sdk.JavacusGenerator", date = "2026-02-12T11:18:50.087149067+08:00[Asia/Shanghai]")
public class ToolsAdvertiserDiagnosisSuggestionGetV30Filtering {
  public static final String SERIALIZED_NAME_SUGGESTION_TYPE = "suggestion_type";
  @SerializedName(SERIALIZED_NAME_SUGGESTION_TYPE)
  private List<ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType> suggestionType = null;

  public ToolsAdvertiserDiagnosisSuggestionGetV30Filtering() {
  }

  public ToolsAdvertiserDiagnosisSuggestionGetV30Filtering suggestionType(List<ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType> suggestionType) {
    
    this.suggestionType = suggestionType;
    return this;
  }

  public ToolsAdvertiserDiagnosisSuggestionGetV30Filtering addSuggestionTypeItem(ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType suggestionTypeItem) {
    if (this.suggestionType == null) {
      this.suggestionType = new ArrayList<>();
    }
    this.suggestionType.add(suggestionTypeItem);
    return this;
  }

   /**
   * 
   * @return suggestionType
  **/
  @javax.annotation.Nullable
  public List<ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType> getSuggestionType() {
    return suggestionType;
  }


  public void setSuggestionType(List<ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType> suggestionType) {
    this.suggestionType = suggestionType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolsAdvertiserDiagnosisSuggestionGetV30Filtering toolsAdvertiserDiagnosisSuggestionGetV30Filtering = (ToolsAdvertiserDiagnosisSuggestionGetV30Filtering) o;
    return Objects.equals(this.suggestionType, toolsAdvertiserDiagnosisSuggestionGetV30Filtering.suggestionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suggestionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolsAdvertiserDiagnosisSuggestionGetV30Filtering {\n");
    sb.append("    suggestionType: ").append(toIndentedString(suggestionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("suggestion_type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }


  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ToolsAdvertiserDiagnosisSuggestionGetV30Filtering.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ToolsAdvertiserDiagnosisSuggestionGetV30Filtering' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ToolsAdvertiserDiagnosisSuggestionGetV30Filtering> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ToolsAdvertiserDiagnosisSuggestionGetV30Filtering.class));

       return (TypeAdapter<T>) new TypeAdapter<ToolsAdvertiserDiagnosisSuggestionGetV30Filtering>() {
           @Override
           public void write(JsonWriter out, ToolsAdvertiserDiagnosisSuggestionGetV30Filtering value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ToolsAdvertiserDiagnosisSuggestionGetV30Filtering read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ToolsAdvertiserDiagnosisSuggestionGetV30Filtering given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ToolsAdvertiserDiagnosisSuggestionGetV30Filtering
  * @throws IOException if the JSON string is invalid with respect to ToolsAdvertiserDiagnosisSuggestionGetV30Filtering
  */
  public static ToolsAdvertiserDiagnosisSuggestionGetV30Filtering fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ToolsAdvertiserDiagnosisSuggestionGetV30Filtering.class);
  }

 /**
  * Convert an instance of ToolsAdvertiserDiagnosisSuggestionGetV30Filtering to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

