/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.94
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 
 */
@JsonAdapter(ToolsExtremeMaterialLimitGetV30NotificationType.Adapter.class)
public enum ToolsExtremeMaterialLimitGetV30NotificationType {
  
  LIMIT("LIMIT"),
  
  WARN("WARN");

  private String value;

  ToolsExtremeMaterialLimitGetV30NotificationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ToolsExtremeMaterialLimitGetV30NotificationType fromValue(String value) {
    for (ToolsExtremeMaterialLimitGetV30NotificationType b : ToolsExtremeMaterialLimitGetV30NotificationType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ToolsExtremeMaterialLimitGetV30NotificationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ToolsExtremeMaterialLimitGetV30NotificationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ToolsExtremeMaterialLimitGetV30NotificationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ToolsExtremeMaterialLimitGetV30NotificationType.fromValue(value);
    }
  }
}

