/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 
 */
@JsonAdapter(ToolsAdConvertQueryV2PromotionContent.Adapter.class)
public enum ToolsAdConvertQueryV2PromotionContent {
  
  EXTERNAL_URL("EXTERNAL_URL"),
  
  MICRO_APP("MICRO_APP"),
  
  DOWNLOAD_URL("DOWNLOAD_URL"),
  
  QUICK_APP_URL("QUICK_APP_URL"),
  
  GOODS_LINK("GOODS_LINK"),
  
  LIVE_ROOM("LIVE_ROOM"),
  
  DOUYIN("DOUYIN"),
  
  THIRD_PARTY("THIRD_PARTY"),
  
  NORMAL("NORMAL"),
  
  AWEME_HOME_PAGE("AWEME_HOME_PAGE"),
  
  SHOP("SHOP");

  private String value;

  ToolsAdConvertQueryV2PromotionContent(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ToolsAdConvertQueryV2PromotionContent fromValue(String value) {
    for (ToolsAdConvertQueryV2PromotionContent b : ToolsAdConvertQueryV2PromotionContent.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ToolsAdConvertQueryV2PromotionContent> {
    @Override
    public void write(final JsonWriter jsonWriter, final ToolsAdConvertQueryV2PromotionContent enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ToolsAdConvertQueryV2PromotionContent read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ToolsAdConvertQueryV2PromotionContent.fromValue(value);
    }
  }
}

