/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 
 */
@JsonAdapter(ToolsWechatGameListV30DataListMidPaymentTierRange.Adapter.class)
public enum ToolsWechatGameListV30DataListMidPaymentTierRange {
  
  ABOVE_500("ABOVE_500"),
  
  BELOW_100("BELOW_100"),
  
  FROM_100_TO_500("FROM_100_TO_500");

  private String value;

  ToolsWechatGameListV30DataListMidPaymentTierRange(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ToolsWechatGameListV30DataListMidPaymentTierRange fromValue(String value) {
    for (ToolsWechatGameListV30DataListMidPaymentTierRange b : ToolsWechatGameListV30DataListMidPaymentTierRange.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ToolsWechatGameListV30DataListMidPaymentTierRange> {
    @Override
    public void write(final JsonWriter jsonWriter, final ToolsWechatGameListV30DataListMidPaymentTierRange enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ToolsWechatGameListV30DataListMidPaymentTierRange read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ToolsWechatGameListV30DataListMidPaymentTierRange.fromValue(value);
    }
  }
}

